# base settings
title:        ROBOT
author:       Gary
email:        liguiyand@163.com
description:  All things for making robots.
baseurl:      ""
url:          "" # the base hostname & protocol for your site, e.g. http://example.com

# build settings
markdown:       kramdown
encoding:       utf-8
theme:          jekyll-theme-clean-blog
paginate:       5
paginate_path:  "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

# local settings
port: 8089